### PR TITLE
Do not create an empty volume before restoration

### PR DESCRIPTION
**Pull request by marciobarbosa**
Currently, the restore daemon checks if the volume received from the dump
server is present in its local cell. If not, the following actions will be
performed by this process:

1. An empty volume with the same name will be created;
2. The replicas will be added;
3. The empty volume will be released;

At this point, the dump file received from the dump server is restored on
top of this empty volume. After that, the volume in question is released.

Unfortunately, this current approach can be problematic. As one can
imagine, the update time of the empty volume is gonna be newer than the
update time of the volume being restored. As a result, the incremental
release of the latter will not update the replicas correctly.

To fix this problem, do not create an empty volume even if the volume in
question does not exist in the destination cell. Instead, let the restore
operation create this volume for us (if necessary).

### CODE REVIEW

**Comment by adeason** [comment]
One issue: on first sync, if the restore fails for any reason, we'll retry the _do_restore, and then we'll see that the volume already exists. So, after the restore we won't do the addsites, which is a problem. Correct? (This is way less important than the problem you're solving, but it is still a problem.)

I think that's the reason I originally did the blank create/release; I wanted to do the addsites before the lengthy "vos restore", but we can't do addsites before the volume exists.

This can be worked around by doing the addsites in parallel of the restore, but that's ugly and not great. Or we could separately test for the existence of the RO sites separately, but that means we could call the picksites script twice (once for RW and once for RO sites), and if we fail in the middle of creating the rosites, then we'd maybe be running with fewer ro sites than we're supposed to. That's not as terrible, but not quite ideal.

I think this is more properly solved by transitioning to a new state specifically for new volumes (call it RESTORE_NEWVOLUME or RESTORE_CREATE or something). That state would do the same thing as _do_restore, but assume that the volume doesn't already exist. At the beginning of _do_restore, you'd check if the volume exists, and if it doesn't, then immediately transition the job to RESTORE_NEWVOLUME and return. The code for _do_restore and _do_restore_newvolume (or whatever) would just go through a common function with an added arg.

**Comment by marciobarbosa** [comment]
One issue: on first sync, if the restore fails for any reason, we'll retry the _do_restore, and then we'll see that the volume already exists. So, after the restore we won't do the addsites, which is a problem. Correct? (This is way less important than the problem you're solving, but it is still a problem.)

I have tested this possibility. In order to check if the volume exist, we check if this volume is present in the vldb. IIRC, the vldb entry is only created at the very end of the restore (when everything worked as expected). However, we can still have a problem like that if, as an example, the fist vos->addsite fails. At this point, we already have an entry for this volume in the vldb and we didn’t have the chance to run vos->addsite for the other sites (because the first vos->addsite failed).

This can be worked around by doing the addsites in parallel of the restore, but that's ugly and not great. Or we could separately test for the existence of the RO sites separately, but that means we could call the picksites script twice (once for RW and once for RO sites), and if we fail in the middle of creating the rosites, then we'd maybe be running with fewer ro sites than we're supposed to. That's not as terrible, but not quite ideal.

I spent sometime thinking about a function that would check if the ro-sites (provided by pick_sites) have a replica. But the reason why something like that would not work is because pick_sites can be changed. So, I got the conclusion that problems with vos->addsite (only executed once when the volume does not exist) would be rare and the consequences would be acceptable.

I think this is more properly solved by transitioning to a new state specifically for new volumes (call it RESTORE_NEWVOLUME or RESTORE_CREATE or something). That state would do the same thing as _do_restore, but assume that the volume doesn't already exist. At the beginning of _do_restore, you'd check if the volume exists, and if it doesn't, then immediately transition the job to RESTORE_NEWVOLUME and return. The code for _do_restore and _do_restore_newvolume (or whatever) would just go through a common function with an added arg.

I am not sure if something like that would work. Let’s say we failed while running vos->addsite for the second read-only site. In this case, we would try the RESTORE_NEWVOLUME state again. But the first read-only site already has the replica. This means that vos->addsite will always fail for the first ro-site (?). As a result, we would be stuck in this state.

**Comment by adeason** [comment]
On Mon, 09 Jul 2018 15:18:34 -0700
Marcio Brito Barbosa <notifications@github.com> wrote:

> I have tested this possibility. In order to check if the volume exist,
> we check if this volume is present in the vldb. IIRC, the vldb entry
> is only created at the very end of the restore (when everything worked
> as expected).

Okay, in that case I agree this isn't a problem (or is a small enough
problem). Issues with addsite should indeed be rare, and I think the
same issue would have happened before this commit, if an addsite failed.

However, with this commit, if the restore fails, won't we be left with
some junk leftover on the volserver, or does it get removed
automatically? If it is left as a partially-restored volume that doesn't
even have an entry in the vldb, that's going to be hard for an
administrator to find, which is pretty annoying.

Or even if that junk is left behind now, maybe fixing that should just
be a matter for the openafs volserver and not cellcc's problem. Since
that's just a matter for however 'vos restore' works.

>> I think this is more properly solved by transitioning to a new state
>> specifically for new volumes (call it RESTORE_NEWVOLUME or
>> RESTORE_CREATE or something). That state would do the same thing as
>> _do_restore, but assume that the volume doesn't already exist. At the
>> beginning of _do_restore, you'd check if the volume exists, and if it
>> doesn't, then immediately transition the job to RESTORE_NEWVOLUME and
>> return. The code for _do_restore and _do_restore_newvolume (or
>> whatever) would just go through a common function with an added arg.
> 
> I am not sure if something like that would work. Let's say we failed
> while running vos->addsite for the second read-only site. In this
> case, we would try the RESTORE_NEWVOLUME state again. But the first
> read-only site already has the replica. This means that vos->addsite
> will always fail for the first ro-site (?). As a result, we would be
> stuck in this state.

The idea is that RESTORE_NEWVOLUME would first delete the volume before
doing anything. That means removing all readonly copies and the rw, and
re-running picksites.

But that's only _if_ we do something like RESTORE_NEWVOLUME. Based on
the above discussion, maybe that's not worth doing at all.

-- 
Andrew Deason
adeason@dson.org

**Comment by adeason** [comment]
pull request #8 was merged instead of this

**Pull request closed without merging**
